
name: Build aria2c {i686, x86_64} for {Windows, linux}

on:
  release:
    types: [published]

jobs:
  build-aria2-mingw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build aria2 Docker image
        run: docker build -t aria2_mingw -f Dockerfile.i686.x86_64.mingw .
      - name: Create a container
        id: ccont
        run: echo "id=$(docker create aria2_mingw /bin/bash)" >> "$GITHUB_OUTPUT"
      - name: Copy built aria2 - aria2c.exe
        run: |
          mkdir -p aria2/i686 aria2/x86_64
          docker cp ${{steps.ccont.outputs.id}}:/i686/aria2c.exe aria2/i686/
          docker cp ${{steps.ccont.outputs.id}}:/x86_64/aria2c.exe aria2/x86_64/
          cd aria2
          zip aria2-i686-win.zip i686/*
          zip aria2-x86_64-win.zip x86_64/*
      - name: rm the container and image
        run: |
          docker rm ${{steps.ccont.outputs.id}}
          docker image rm aria2_mingw
      - name: Upload release asset i686 & x86_64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: aria2/aria2-*.zip
          overwrite: true
          file_glob: true
  build-aria2-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build aria2 Docker image
        run: docker build -t aria2_linux -f Dockerfile.i686.x86_64.linux .
      - name: Create a container
        id: ccont
        run: echo "id=$(docker create aria2_linux /bin/bash)" >> "$GITHUB_OUTPUT"
      - name: Copy built aria2 - aria2c
        run: |
          mkdir -p aria2/i686 aria2/x86_64
          docker cp ${{steps.ccont.outputs.id}}:/i686/aria2c aria2/i686/
          docker cp ${{steps.ccont.outputs.id}}:/x86_64/aria2c aria2/x86_64/
          cd aria2
          tar Jcvf aria2-i686-linux.tar.xz i686/*
          tar Jcvf aria2-x86_64-linux.tar.xz x86_64/*
      - name: rm the container and image
        run: |
          docker rm ${{steps.ccont.outputs.id}}
          docker image rm aria2_linux
      - name: Upload release asset i686 & x86_64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: aria2/aria2-*.tar.xz
          overwrite: true
          file_glob: true